#!/bin/bash
BASE="$(cd `dirname "$0"` && pwd)"

main () {
    local cmd="$1"
    case $cmd in
        'run')
            shift
            run_console "$@"
            ;;
        'setup')
            shift
            setup "$@"
            ;;
        'test')
            shift
            run_tests "$@"
            ;;
        'clean')
            shift
            clean "$@"
            ;;
        * )
            echo "
Exiting without running any operations.
Possible operations include:

  run - Run the console app (prints to console)
    Usage: ./manage.sh run

  setup - Install dependencies.
    Usage: ./manage.sh setup

  test - Run tests.
    Usage: ./manage.sh test

  clean - Remove everything generated by this script.
    Usage: ./manage.sh clean
            "
            ;;
    esac
}

run_console () {
    echo "Press CTRL-C to quit."
    node "$BASE/index.js"
}

setup () {
    if ! [ -d "$BASE/node_modules" ]; then
        cd "$BASE/"
        mkdir "$BASE/node_modules"
        npm install
    fi
}

run_tests () {
    setup
    "$BASE/node_modules/.bin/mocha"
}

clean () {
    rm -rf "$BASE/node_modules/"
    echo "removed node_modules"
}

main "$@"
